-- Seed the GTM ExitIQ question bank (mirrors the embedded bank in the prototype).
insert into public.questionnaire_versions (version, label, is_active) values (1, 'GTM ExitIQ launch bank', true);

insert into public.qv_categories (version_id, key, name_en, name_de, description_en, description_de, weight_x, weight_y, sort_order) select v.id, $txt$financial_transparency$txt$, $txt$Financial Transparency & Performance$txt$, $txt$Finanzielle Transparenz & Performance$txt$, $txt$Clean numbers, audited statements, separation of owner expenses.$txt$, $txt$Saubere Zahlen, testierte Abschlüsse, Trennung privater Kosten.$txt$, 0.18, 0.3, 0 from public.questionnaire_versions v where v.version = 1;
insert into public.qv_categories (version_id, key, name_en, name_de, description_en, description_de, weight_x, weight_y, sort_order) select v.id, $txt$owner_independence$txt$, $txt$Owner Independence$txt$, $txt$Unternehmer-Unabhängigkeit$txt$, $txt$Management depth, documented knowledge, succession planning.$txt$, $txt$Führungstiefe, dokumentiertes Wissen, Nachfolgeplanung.$txt$, 0.28, 0.02, 10 from public.questionnaire_versions v where v.version = 1;
insert into public.qv_categories (version_id, key, name_en, name_de, description_en, description_de, weight_x, weight_y, sort_order) select v.id, $txt$market_position$txt$, $txt$Market Position & Moat$txt$, $txt$Marktposition & Wettbewerbsvorteil$txt$, $txt$Competitive moat, IP, brand strength, roadmap clarity.$txt$, $txt$Wettbewerbsvorteil, IP, Marke, Roadmap-Klarheit.$txt$, 0.02, 0.32, 20 from public.questionnaire_versions v where v.version = 1;
insert into public.qv_categories (version_id, key, name_en, name_de, description_en, description_de, weight_x, weight_y, sort_order) select v.id, $txt$customer_supplier$txt$, $txt$Customer & Supplier Structure$txt$, $txt$Kunden- & Lieferantenstruktur$txt$, $txt$Revenue concentration, recurring income, supplier risk.$txt$, $txt$Umsatzkonzentration, wiederkehrende Erlöse, Lieferantenrisiko.$txt$, 0.12, 0.16, 30 from public.questionnaire_versions v where v.version = 1;
insert into public.qv_categories (version_id, key, name_en, name_de, description_en, description_de, weight_x, weight_y, sort_order) select v.id, $txt$processes_scalability$txt$, $txt$Processes, Scalability & Infrastructure$txt$, $txt$Prozesse, Skalierbarkeit & Infrastruktur$txt$, $txt$Documented SOPs, modern systems, growth headroom.$txt$, $txt$Dokumentierte SOPs, moderne Systeme, Wachstumsspielraum.$txt$, 0.12, 0.1, 40 from public.questionnaire_versions v where v.version = 1;
insert into public.qv_categories (version_id, key, name_en, name_de, description_en, description_de, weight_x, weight_y, sort_order) select v.id, $txt$people_culture$txt$, $txt$Personnel & Corporate Culture$txt$, $txt$Personal & Unternehmenskultur$txt$, $txt$Retention, key-man risk, talent pipeline, ESG.$txt$, $txt$Bindung, Key-Man-Risiko, Talent-Pipeline, ESG.$txt$, 0.08, 0.08, 50 from public.questionnaire_versions v where v.version = 1;
insert into public.qv_categories (version_id, key, name_en, name_de, description_en, description_de, weight_x, weight_y, sort_order) select v.id, $txt$legal_cleanliness$txt$, $txt$Legal & Compliance Cleanliness$txt$, $txt$Rechtliche & Compliance-Sauberkeit$txt$, $txt$IP ownership, contract currency, GDPR, no open litigation.$txt$, $txt$IP-Eigentum, aktuelle Verträge, DSGVO, keine offenen Klagen.$txt$, 0.2, 0.02, 60 from public.questionnaire_versions v where v.version = 1;

insert into public.qv_questions (version_id, category_id, question_key, text_en, text_de, info_en, info_de, is_red_flag, is_active, sort_order, sectors, is_follow_up, follow_up_question_key, follow_up_condition) select v.id, c.id, $txt$ft-1$txt$, $txt$Does monthly controlling exist with target/actual comparisons and integrated 3-5 year planning?$txt$, $txt$Gibt es ein monatliches Controlling mit Soll-Ist-Vergleich und integrierter 3-5-Jahres-Planung?$txt$, null, null, false, true, 0, null, false, null, null from public.questionnaire_versions v join public.qv_categories c on c.version_id = v.id and c.key = $txt$financial_transparency$txt$ where v.version = 1;
insert into public.question_options (question_id, option_key, text_en, text_de, score, sort_order) select id, 'optimal', $txt$Fully integrated reporting system; monthly steering meetings; rolling 5-year planning established$txt$, $txt$Vollständig integriertes Reporting; monatliche Steuerungsmeetings; rollierende 5-Jahres-Planung etabliert$txt$, 2, 0 from public.qv_questions where question_key = $txt$ft-1$txt$;
insert into public.question_options (question_id, option_key, text_en, text_de, score, sort_order) select id, 'good', $txt$Monthly reports available; annual planning exists; target/actual analyses occur irregularly$txt$, $txt$Monatliche Berichte vorhanden; Jahresplanung existiert; Soll-Ist-Analysen erfolgen unregelmäßig$txt$, 1, 1 from public.qv_questions where question_key = $txt$ft-1$txt$;
insert into public.question_options (question_id, option_key, text_en, text_de, score, sort_order) select id, 'low', $txt$Ad-hoc reporting; focus on liquidity instead of P&L management; no reliable long-term planning$txt$, $txt$Ad-hoc-Reporting; Fokus auf Liquidität statt GuV-Steuerung; keine belastbare Langfristplanung$txt$, 0, 2 from public.qv_questions where question_key = $txt$ft-1$txt$;

insert into public.qv_questions (version_id, category_id, question_key, text_en, text_de, info_en, info_de, is_red_flag, is_active, sort_order, sectors, is_follow_up, follow_up_question_key, follow_up_condition) select v.id, c.id, $txt$ft-2$txt$, $txt$Are audited financial statements available for the last three years and is the accounting "due diligence-ready"?$txt$, $txt$Liegen testierte Abschlüsse der letzten drei Jahre vor und ist die Buchhaltung „Due-Diligence-fähig“?$txt$, $txt$Acquirers require independently verified financials. Unaudited numbers carry significant due-diligence risk and suppress valuations.$txt$, $txt$Käufer verlangen unabhängig geprüfte Zahlen. Nicht testierte Abschlüsse bergen erhebliches Due-Diligence-Risiko und drücken die Bewertung.$txt$, true, true, 10, null, false, null, null from public.questionnaire_versions v join public.qv_categories c on c.version_id = v.id and c.key = $txt$financial_transparency$txt$ where v.version = 1;
insert into public.question_options (question_id, option_key, text_en, text_de, score, sort_order) select id, 'optimal', $txt$Complete audited financial statements for last 3 years; "Financial Factbook" prepared$txt$, $txt$Vollständig testierte Abschlüsse der letzten 3 Jahre; „Financial Factbook“ vorbereitet$txt$, 2, 0 from public.qv_questions where question_key = $txt$ft-2$txt$;
insert into public.question_options (question_id, option_key, text_en, text_de, score, sort_order) select id, 'good', $txt$Tax advisor statements available; documentation largely prepared for due diligence$txt$, $txt$Steuerberater-Abschlüsse vorhanden; Dokumentation für die Due Diligence weitgehend vorbereitet$txt$, 1, 1 from public.qv_questions where question_key = $txt$ft-2$txt$;
insert into public.question_options (question_id, option_key, text_en, text_de, score, sort_order) select id, 'low', $txt$Financial statements incomplete or delayed; documentation does not meet professional investor standards$txt$, $txt$Abschlüsse unvollständig oder verspätet; Dokumentation entspricht nicht dem Standard professioneller Investoren$txt$, 0, 2 from public.qv_questions where question_key = $txt$ft-2$txt$;

insert into public.qv_questions (version_id, category_id, question_key, text_en, text_de, info_en, info_de, is_red_flag, is_active, sort_order, sectors, is_follow_up, follow_up_question_key, follow_up_condition) select v.id, c.id, $txt$ft-4$txt$, $txt$What percentage of revenue is contractually secured and recurring?$txt$, $txt$Welcher Anteil des Umsatzes ist vertraglich abgesichert und wiederkehrend?$txt$, null, null, false, true, 20, null, false, null, null from public.questionnaire_versions v join public.qv_categories c on c.version_id = v.id and c.key = $txt$financial_transparency$txt$ where v.version = 1;
insert into public.question_options (question_id, option_key, text_en, text_de, score, sort_order) select id, 'optimal', $txt$Over 70% of revenue based on subscriptions, maintenance contracts, or long-term framework agreements (>2 years)$txt$, $txt$Über 70% (z. B. Subscriptions, Wartungsverträge oder Rahmenverträge >2 Jahre)$txt$, 2, 0 from public.qv_questions where question_key = $txt$ft-4$txt$;
insert into public.question_options (question_id, option_key, text_en, text_de, score, sort_order) select id, 'good', $txt$Mix of long-term contracts and stable existing customers; current trading within budget range$txt$, $txt$30-70% mit Mix aus längerfristigen Verträgen und stabilem Bestandskundengeschäft$txt$, 1, 1 from public.qv_questions where question_key = $txt$ft-4$txt$;
insert into public.question_options (question_id, option_key, text_en, text_de, score, sort_order) select id, 'low', $txt$Focus on short-term project business; no contractual customer commitment; high dependency on new customers$txt$, $txt$Unter 30% mit Fokus auf kurzfristiges Projektgeschäft ohne vertragliche Bindung$txt$, 0, 2 from public.qv_questions where question_key = $txt$ft-4$txt$;

insert into public.qv_questions (version_id, category_id, question_key, text_en, text_de, info_en, info_de, is_red_flag, is_active, sort_order, sectors, is_follow_up, follow_up_question_key, follow_up_condition) select v.id, c.id, $txt$oi-1$txt$, $txt$Can the company operate profitably for three months without any owner decisions?$txt$, $txt$Kann das Unternehmen drei Monate ohne Entscheidungen des Inhabers profitabel arbeiten?$txt$, $txt$Owner dependency is the single biggest discount applied by acquirers. A business that cannot run without its founder is often unsellable at fair value.$txt$, $txt$Inhaberabhängigkeit ist der größte einzelne Abschlag, den Käufer ansetzen. Ein Unternehmen, das ohne seinen Gründer nicht läuft, ist zu einem fairen Preis oft nicht verkäuflich.$txt$, true, true, 30, null, false, null, null from public.questionnaire_versions v join public.qv_categories c on c.version_id = v.id and c.key = $txt$owner_independence$txt$ where v.version = 1;
insert into public.question_options (question_id, option_key, text_en, text_de, score, sort_order) select id, 'optimal', $txt$Owner no longer in daily operations; management makes operational decisions autonomously$txt$, $txt$Inhaber nicht mehr im Tagesgeschäft; das Management entscheidet operativ eigenständig$txt$, 2, 0 from public.qv_questions where question_key = $txt$oi-1$txt$;
insert into public.question_options (question_id, option_key, text_en, text_de, score, sort_order) select id, 'good', $txt$Owner needed for strategic topics and key accounts; core processes run stably without them$txt$, $txt$Inhaber für strategische Themen und Key Accounts nötig; Kernprozesse laufen stabil ohne ihn$txt$, 1, 1 from public.qv_questions where question_key = $txt$oi-1$txt$;
insert into public.question_options (question_id, option_key, text_en, text_de, score, sort_order) select id, 'low', $txt$Owner is "bottleneck" for all important approvals and operational processes$txt$, $txt$Inhaber ist „Flaschenhals“ für alle wichtigen Freigaben und operativen Abläufe$txt$, 0, 2 from public.qv_questions where question_key = $txt$oi-1$txt$;

insert into public.qv_questions (version_id, category_id, question_key, text_en, text_de, info_en, info_de, is_red_flag, is_active, sort_order, sectors, is_follow_up, follow_up_question_key, follow_up_condition) select v.id, c.id, $txt$oi-2$txt$, $txt$Is business-critical know-how (technical/sales) documented in systems?$txt$, $txt$Ist geschäftskritisches Know-how (technisch/vertrieblich) in Systemen dokumentiert?$txt$, null, null, false, true, 40, null, false, null, null from public.questionnaire_versions v join public.qv_categories c on c.version_id = v.id and c.key = $txt$owner_independence$txt$ where v.version = 1;
insert into public.question_options (question_id, option_key, text_en, text_de, score, sort_order) select id, 'optimal', $txt$Full documentation of all IP and process knowledge in digital manuals/systems (SOPs)$txt$, $txt$Vollständige Dokumentation von IP und Prozesswissen in digitalen Handbüchern/Systemen (SOPs)$txt$, 2, 0 from public.qv_questions where question_key = $txt$oi-2$txt$;
insert into public.question_options (question_id, option_key, text_en, text_de, score, sort_order) select id, 'good', $txt$Core knowledge partially documented; knowledge transfer to second level initiated$txt$, $txt$Kernwissen teilweise dokumentiert; Wissenstransfer auf die zweite Ebene angestoßen$txt$, 1, 1 from public.qv_questions where question_key = $txt$oi-2$txt$;
insert into public.question_options (question_id, option_key, text_en, text_de, score, sort_order) select id, 'low', $txt$Exclusive knowledge almost only with owner; no written knowledge base available$txt$, $txt$Exklusives Wissen fast nur beim Inhaber; keine schriftliche Wissensbasis vorhanden$txt$, 0, 2 from public.qv_questions where question_key = $txt$oi-2$txt$;

insert into public.qv_questions (version_id, category_id, question_key, text_en, text_de, info_en, info_de, is_red_flag, is_active, sort_order, sectors, is_follow_up, follow_up_question_key, follow_up_condition) select v.id, c.id, $txt$oi-3$txt$, $txt$Does a second management level exist with authority and clear reporting structures?$txt$, $txt$Existiert eine zweite Führungsebene mit Kompetenzen und klaren Berichtsstrukturen?$txt$, null, null, false, true, 50, null, false, null, null from public.questionnaire_versions v join public.qv_categories c on c.version_id = v.id and c.key = $txt$owner_independence$txt$ where v.version = 1;
insert into public.question_options (question_id, option_key, text_en, text_de, score, sort_order) select id, 'optimal', $txt$Experienced management team with power of attorney; clear responsibilities and reporting structures established$txt$, $txt$Erfahrenes Managementteam mit Vollmachten; klare Verantwortlichkeiten und Berichtswege etabliert$txt$, 2, 0 from public.qv_questions where question_key = $txt$oi-3$txt$;
insert into public.question_options (question_id, option_key, text_en, text_de, score, sort_order) select id, 'good', $txt$Management team present but still heavily dependent on owner as corrective$txt$, $txt$Managementteam vorhanden, aber stark auf den Inhaber als Korrektiv angewiesen$txt$, 1, 1 from public.qv_questions where question_key = $txt$oi-3$txt$;
insert into public.question_options (question_id, option_key, text_en, text_de, score, sort_order) select id, 'low', $txt$Flat hierarchy without real delegation; owner decides even minor matters$txt$, $txt$Flache Hierarchie ohne echte Delegation; der Inhaber entscheidet auch Kleinigkeiten$txt$, 0, 2 from public.qv_questions where question_key = $txt$oi-3$txt$;

insert into public.qv_questions (version_id, category_id, question_key, text_en, text_de, info_en, info_de, is_red_flag, is_active, sort_order, sectors, is_follow_up, follow_up_question_key, follow_up_condition) select v.id, c.id, $txt$mp-1$txt$, $txt$Does the company have a unique selling proposition that protects it from price competition?$txt$, $txt$Verfügt das Unternehmen über ein Alleinstellungsmerkmal, das es vor Preiswettbewerb schützt?$txt$, null, null, false, true, 60, null, false, null, null from public.questionnaire_versions v join public.qv_categories c on c.version_id = v.id and c.key = $txt$market_position$txt$ where v.version = 1;
insert into public.question_options (question_id, option_key, text_en, text_de, score, sort_order) select id, 'optimal', $txt$Unique technology or market position; high switching barriers for customers (lock-in)$txt$, $txt$Einzigartige Technologie oder Marktposition; hohe Wechselbarrieren für Kunden (Lock-in)$txt$, 2, 0 from public.qv_questions where question_key = $txt$mp-1$txt$;
insert into public.question_options (question_id, option_key, text_en, text_de, score, sort_order) select id, 'good', $txt$Clear competitive advantage present; market positioning allows above-average prices$txt$, $txt$Klarer Wettbewerbsvorteil vorhanden; die Positionierung erlaubt überdurchschnittliche Preise$txt$, 1, 1 from public.qv_questions where question_key = $txt$mp-1$txt$;
insert into public.question_options (question_id, option_key, text_en, text_de, score, sort_order) select id, 'low', $txt$Interchangeable service offering; competition primarily through price$txt$, $txt$Austauschbares Leistungsangebot; Wettbewerb vor allem über den Preis$txt$, 0, 2 from public.qv_questions where question_key = $txt$mp-1$txt$;

insert into public.qv_questions (version_id, category_id, question_key, text_en, text_de, info_en, info_de, is_red_flag, is_active, sort_order, sectors, is_follow_up, follow_up_question_key, follow_up_condition) select v.id, c.id, $txt$mp-2$txt$, $txt$Does the company operate in a growing market segment with a positive future outlook?$txt$, $txt$Ist das Unternehmen in einem wachsenden Marktsegment mit positiver Zukunftsaussicht tätig?$txt$, null, null, false, true, 70, null, false, null, null from public.questionnaire_versions v join public.qv_categories c on c.version_id = v.id and c.key = $txt$market_position$txt$ where v.version = 1;
insert into public.question_options (question_id, option_key, text_en, text_de, score, sort_order) select id, 'optimal', $txt$Dynamic growth market; company occupies attractive niches with high margins$txt$, $txt$Dynamischer Wachstumsmarkt; das Unternehmen besetzt attraktive Nischen mit hohen Margen$txt$, 2, 0 from public.qv_questions where question_key = $txt$mp-2$txt$;
insert into public.question_options (question_id, option_key, text_en, text_de, score, sort_order) select id, 'good', $txt$Stable overall market; company can gain market share through targeted acquisition/marketing$txt$, $txt$Stabiler Gesamtmarkt; Marktanteile durch gezielte Akquisition/Marketing gewinnbar$txt$, 1, 1 from public.qv_questions where question_key = $txt$mp-2$txt$;
insert into public.question_options (question_id, option_key, text_en, text_de, score, sort_order) select id, 'low', $txt$Saturated or shrinking market; high consolidation pressure from competitors$txt$, $txt$Gesättigter oder schrumpfender Markt; hoher Konsolidierungsdruck durch Wettbewerber$txt$, 0, 2 from public.qv_questions where question_key = $txt$mp-2$txt$;

insert into public.qv_questions (version_id, category_id, question_key, text_en, text_de, info_en, info_de, is_red_flag, is_active, sort_order, sectors, is_follow_up, follow_up_question_key, follow_up_condition) select v.id, c.id, $txt$mp-3$txt$, $txt$Is the brand established in the market independently of the owner’s name or reputation?$txt$, $txt$Ist die Marke unabhängig vom Namen oder Ruf des Inhabers im Markt etabliert?$txt$, null, null, false, true, 80, null, false, null, null from public.questionnaire_versions v join public.qv_categories c on c.version_id = v.id and c.key = $txt$market_position$txt$ where v.version = 1;
insert into public.question_options (question_id, option_key, text_en, text_de, score, sort_order) select id, 'optimal', $txt$Brand stands on its own; high recognition; branding is person-independent$txt$, $txt$Die Marke steht für sich; hohe Bekanntheit; Branding ist personenunabhängig$txt$, 2, 0 from public.qv_questions where question_key = $txt$mp-3$txt$;
insert into public.question_options (question_id, option_key, text_en, text_de, score, sort_order) select id, 'good', $txt$Brand well established; connection to owner being gradually reduced$txt$, $txt$Marke gut etabliert; die Verbindung zum Inhaber wird schrittweise reduziert$txt$, 1, 1 from public.qv_questions where question_key = $txt$mp-3$txt$;
insert into public.question_options (question_id, option_key, text_en, text_de, score, sort_order) select id, 'low', $txt$Brand reputation inseparably linked to the entrepreneur’s person$txt$, $txt$Der Ruf der Marke ist untrennbar mit der Person des Unternehmers verbunden$txt$, 0, 2 from public.qv_questions where question_key = $txt$mp-3$txt$;

insert into public.qv_questions (version_id, category_id, question_key, text_en, text_de, info_en, info_de, is_red_flag, is_active, sort_order, sectors, is_follow_up, follow_up_question_key, follow_up_condition) select v.id, c.id, $txt$cs-1$txt$, $txt$Does the largest single customer generate less than 10-15% of total revenue?$txt$, $txt$Erzielt der größte Einzelkunde weniger als 10-15% des Gesamtumsatzes?$txt$, $txt$High customer concentration is a key deal-breaker. Acquirers typically want no single customer exceeding 20-25% of revenue.$txt$, $txt$Hohe Kundenkonzentration ist ein zentraler Deal-Breaker. Käufer erwarten in der Regel, dass kein Einzelkunde mehr als 20-25% des Umsatzes ausmacht.$txt$, true, true, 90, null, false, null, null from public.questionnaire_versions v join public.qv_categories c on c.version_id = v.id and c.key = $txt$customer_supplier$txt$ where v.version = 1;
insert into public.question_options (question_id, option_key, text_en, text_de, score, sort_order) select id, 'optimal', $txt$Highly diversified portfolio; no customer contributes significantly to risk$txt$, $txt$Stark diversifiziertes Portfolio; kein Kunde trägt wesentlich zum Risiko bei$txt$, 2, 0 from public.qv_questions where question_key = $txt$cs-1$txt$;
insert into public.question_options (question_id, option_key, text_en, text_de, score, sort_order) select id, 'good', $txt$Focus on top customers present, but no cluster risk over 20% per customer$txt$, $txt$Schwerpunkt auf Top-Kunden vorhanden, aber kein Klumpenrisiko über 20% pro Kunde$txt$, 1, 1 from public.qv_questions where question_key = $txt$cs-1$txt$;
insert into public.question_options (question_id, option_key, text_en, text_de, score, sort_order) select id, 'low', $txt$Extreme dependency; a single customer generates >25% of revenue$txt$, $txt$Extreme Abhängigkeit; ein einzelner Kunde erzeugt >25% des Umsatzes$txt$, 0, 2 from public.qv_questions where question_key = $txt$cs-1$txt$;

insert into public.qv_questions (version_id, category_id, question_key, text_en, text_de, info_en, info_de, is_red_flag, is_active, sort_order, sectors, is_follow_up, follow_up_question_key, follow_up_condition) select v.id, c.id, $txt$cs-3$txt$, $txt$Are the top 10 customer relationships secured by long-term contracts?$txt$, $txt$Sind die Top-10-Kundenbeziehungen durch langfristige Verträge abgesichert?$txt$, null, null, false, true, 100, null, false, null, null from public.questionnaire_versions v join public.qv_categories c on c.version_id = v.id and c.key = $txt$customer_supplier$txt$ where v.version = 1;
insert into public.question_options (question_id, option_key, text_en, text_de, score, sort_order) select id, 'optimal', $txt$Long-term framework contracts with termination protection and price adjustment clauses$txt$, $txt$Langfristige Rahmenverträge mit Kündigungsschutz und Preisanpassungsklauseln$txt$, 2, 0 from public.qv_questions where question_key = $txt$cs-3$txt$;
insert into public.question_options (question_id, option_key, text_en, text_de, score, sort_order) select id, 'good', $txt$Verbal commitments backed by written standard contracts; change-of-control reviewed$txt$, $txt$Mündliche Zusagen durch schriftliche Standardverträge unterlegt; Change-of-Control geprüft$txt$, 1, 1 from public.qv_questions where question_key = $txt$cs-3$txt$;
insert into public.question_options (question_id, option_key, text_en, text_de, score, sort_order) select id, 'low', $txt$Primarily spot business or outdated contracts without legal security in a sale$txt$, $txt$Überwiegend Spot-Geschäft oder veraltete Verträge ohne Rechtssicherheit im Verkaufsfall$txt$, 0, 2 from public.qv_questions where question_key = $txt$cs-3$txt$;

insert into public.qv_questions (version_id, category_id, question_key, text_en, text_de, info_en, info_de, is_red_flag, is_active, sort_order, sectors, is_follow_up, follow_up_question_key, follow_up_condition) select v.id, c.id, $txt$cs-4$txt$, $txt$Is the business model diversified against crises in a single industry?$txt$, $txt$Ist das Geschäftsmodell gegen Krisen einer einzelnen Branche diversifiziert?$txt$, null, null, false, true, 110, null, false, null, null from public.questionnaire_versions v join public.qv_categories c on c.version_id = v.id and c.key = $txt$customer_supplier$txt$ where v.version = 1;
insert into public.question_options (question_id, option_key, text_en, text_de, score, sort_order) select id, 'optimal', $txt$Diversified customer base across different industries and regions$txt$, $txt$Diversifizierte Kundenbasis über verschiedene Branchen und Regionen$txt$, 2, 0 from public.qv_questions where question_key = $txt$cs-4$txt$;
insert into public.question_options (question_id, option_key, text_en, text_de, score, sort_order) select id, 'good', $txt$Focus in one industry, but initial success in opening new markets$txt$, $txt$Schwerpunkt in einer Branche, aber erste Erfolge bei der Öffnung neuer Märkte$txt$, 1, 1 from public.qv_questions where question_key = $txt$cs-4$txt$;
insert into public.question_options (question_id, option_key, text_en, text_de, score, sort_order) select id, 'low', $txt$100% focus on one volatile industry; no compensation possible$txt$, $txt$100% Fokus auf eine volatile Branche; keine Kompensation möglich$txt$, 0, 2 from public.qv_questions where question_key = $txt$cs-4$txt$;

insert into public.qv_questions (version_id, category_id, question_key, text_en, text_de, info_en, info_de, is_red_flag, is_active, sort_order, sectors, is_follow_up, follow_up_question_key, follow_up_condition) select v.id, c.id, $txt$ps-1$txt$, $txt$Are written Standard Operating Procedures (SOPs) available for all core processes?$txt$, $txt$Liegen für alle Kernprozesse schriftliche Standardarbeitsanweisungen (SOPs) vor?$txt$, null, null, false, true, 120, null, false, null, null from public.questionnaire_versions v join public.qv_categories c on c.version_id = v.id and c.key = $txt$processes_scalability$txt$ where v.version = 1;
insert into public.question_options (question_id, option_key, text_en, text_de, score, sort_order) select id, 'optimal', $txt$Complete documentation in a process manual; all procedures are replicable$txt$, $txt$Vollständige Dokumentation in einem Prozesshandbuch; alle Abläufe sind reproduzierbar$txt$, 2, 0 from public.qv_questions where question_key = $txt$ps-1$txt$;
insert into public.question_options (question_id, option_key, text_en, text_de, score, sort_order) select id, 'good', $txt$Core processes documented; organisation with clear responsibilities implemented$txt$, $txt$Kernprozesse dokumentiert; Organisation mit klaren Verantwortlichkeiten umgesetzt$txt$, 1, 1 from public.qv_questions where question_key = $txt$ps-1$txt$;
insert into public.question_options (question_id, option_key, text_en, text_de, score, sort_order) select id, 'low', $txt$Knowledge about processes is purely implicit; "wild growth" in task handling$txt$, $txt$Prozesswissen ist rein implizit; „Wildwuchs“ in der Aufgabenbearbeitung$txt$, 0, 2 from public.qv_questions where question_key = $txt$ps-1$txt$;

insert into public.qv_questions (version_id, category_id, question_key, text_en, text_de, info_en, info_de, is_red_flag, is_active, sort_order, sectors, is_follow_up, follow_up_question_key, follow_up_condition) select v.id, c.id, $txt$ps-2$txt$, $txt$Is the technology stack modern, secure, and without significant legacy issues?$txt$, $txt$Ist der Technologie-Stack modern, sicher und ohne wesentliche Altlasten?$txt$, null, null, false, true, 130, null, false, null, null from public.questionnaire_versions v join public.qv_categories c on c.version_id = v.id and c.key = $txt$processes_scalability$txt$ where v.version = 1;
insert into public.question_options (question_id, option_key, text_en, text_de, score, sort_order) select id, 'optimal', $txt$Modern cloud-based systems; IT security standards met; no investment backlog$txt$, $txt$Moderne cloudbasierte Systeme; IT-Sicherheitsstandards erfüllt; kein Investitionsstau$txt$, 2, 0 from public.qv_questions where question_key = $txt$ps-2$txt$;
insert into public.question_options (question_id, option_key, text_en, text_de, score, sort_order) select id, 'good', $txt$Stable IT landscape; digitalization concept being successively implemented$txt$, $txt$Stabile IT-Landschaft; Digitalisierungskonzept wird sukzessive umgesetzt$txt$, 1, 1 from public.qv_questions where question_key = $txt$ps-2$txt$;
insert into public.question_options (question_id, option_key, text_en, text_de, score, sort_order) select id, 'low', $txt$Outdated systems; manual interfaces; high failure or security risk$txt$, $txt$Veraltete Systeme; manuelle Schnittstellen; hohes Ausfall- oder Sicherheitsrisiko$txt$, 0, 2 from public.qv_questions where question_key = $txt$ps-2$txt$;

insert into public.qv_questions (version_id, category_id, question_key, text_en, text_de, info_en, info_de, is_red_flag, is_active, sort_order, sectors, is_follow_up, follow_up_question_key, follow_up_condition) select v.id, c.id, $txt$ps-3$txt$, $txt$Can revenue be increased by 30% without having to increase fixed costs linearly?$txt$, $txt$Kann der Umsatz um 30% gesteigert werden, ohne die Fixkosten linear zu erhöhen?$txt$, null, null, false, true, 140, null, false, null, null from public.questionnaire_versions v join public.qv_categories c on c.version_id = v.id and c.key = $txt$processes_scalability$txt$ where v.version = 1;
insert into public.question_options (question_id, option_key, text_en, text_de, score, sort_order) select id, 'optimal', $txt$High economies of scale; infrastructure and capacities offer reserves for strong growth$txt$, $txt$Hohe Skaleneffekte; Infrastruktur und Kapazitäten bieten Reserven für starkes Wachstum$txt$, 2, 0 from public.qv_questions where question_key = $txt$ps-3$txt$;
insert into public.question_options (question_id, option_key, text_en, text_de, score, sort_order) select id, 'good', $txt$Scalability in core area given; additional personnel for growth plannable$txt$, $txt$Skalierbarkeit im Kernbereich gegeben; zusätzliches Personal für Wachstum planbar$txt$, 1, 1 from public.qv_questions where question_key = $txt$ps-3$txt$;
insert into public.question_options (question_id, option_key, text_en, text_de, score, sort_order) select id, 'low', $txt$Capacity limit reached; any growth requires massive capex investments$txt$, $txt$Kapazitätsgrenze erreicht; jedes Wachstum erfordert massive Capex-Investitionen$txt$, 0, 2 from public.qv_questions where question_key = $txt$ps-3$txt$;

insert into public.qv_questions (version_id, category_id, question_key, text_en, text_de, info_en, info_de, is_red_flag, is_active, sort_order, sectors, is_follow_up, follow_up_question_key, follow_up_condition) select v.id, c.id, $txt$pc-1$txt$, $txt$Is the turnover of key performers below industry average?$txt$, $txt$Liegt die Fluktuation der Leistungsträger unter dem Branchendurchschnitt?$txt$, null, null, false, true, 150, null, false, null, null from public.questionnaire_versions v join public.qv_categories c on c.version_id = v.id and c.key = $txt$people_culture$txt$ where v.version = 1;
insert into public.question_options (question_id, option_key, text_en, text_de, score, sort_order) select id, 'optimal', $txt$Very low turnover; employee participation program or incentives established$txt$, $txt$Sehr geringe Fluktuation; Mitarbeiterbeteiligung oder Incentives etabliert$txt$, 2, 0 from public.qv_questions where question_key = $txt$pc-1$txt$;
insert into public.question_options (question_id, option_key, text_en, text_de, score, sort_order) select id, 'good', $txt$Stable workforce; work-life balance conditions are competitive$txt$, $txt$Stabile Belegschaft; Rahmenbedingungen zur Work-Life-Balance sind wettbewerbsfähig$txt$, 1, 1 from public.qv_questions where question_key = $txt$pc-1$txt$;
insert into public.question_options (question_id, option_key, text_en, text_de, score, sort_order) select id, 'low', $txt$High turnover; no employee retention measures; poor workplace climate$txt$, $txt$Hohe Fluktuation; keine Bindungsmaßnahmen; schlechtes Arbeitsklima$txt$, 0, 2 from public.qv_questions where question_key = $txt$pc-1$txt$;

insert into public.qv_questions (version_id, category_id, question_key, text_en, text_de, info_en, info_de, is_red_flag, is_active, sort_order, sectors, is_follow_up, follow_up_question_key, follow_up_condition) select v.id, c.id, $txt$pc-2$txt$, $txt$Are technical experts replaceable, or does success depend on a few "heroes"?$txt$, $txt$Sind Fachexperten ersetzbar oder hängt der Erfolg an einigen „Helden“?$txt$, $txt$Key-man risk is a primary discount applied in due diligence. Buyers want to know the business survives the departure of any single individual.$txt$, $txt$Das Key-Man-Risiko ist ein zentraler Abschlag in der Due Diligence. Käufer wollen wissen, ob das Unternehmen den Abgang einer einzelnen Person übersteht.$txt$, true, true, 160, null, false, null, null from public.questionnaire_versions v join public.qv_categories c on c.version_id = v.id and c.key = $txt$people_culture$txt$ where v.version = 1;
insert into public.question_options (question_id, option_key, text_en, text_de, score, sort_order) select id, 'optimal', $txt$Knowledge is broadly distributed; deputy concept exists for every key position$txt$, $txt$Wissen ist breit verteilt; für jede Schlüsselposition existiert ein Vertretungskonzept$txt$, 2, 0 from public.qv_questions where question_key = $txt$pc-2$txt$;
insert into public.question_options (question_id, option_key, text_en, text_de, score, sort_order) select id, 'good', $txt$Key employees identified; retention measures and knowledge documentation started$txt$, $txt$Schlüsselpersonen identifiziert; Bindungsmaßnahmen und Wissensdokumentation begonnen$txt$, 1, 1 from public.qv_questions where question_key = $txt$pc-2$txt$;
insert into public.question_options (question_id, option_key, text_en, text_de, score, sort_order) select id, 'low', $txt$Company success massively depends on 1-2 critical experts$txt$, $txt$Der Unternehmenserfolg hängt massiv an 1-2 kritischen Experten$txt$, 0, 2 from public.qv_questions where question_key = $txt$pc-2$txt$;

insert into public.qv_questions (version_id, category_id, question_key, text_en, text_de, info_en, info_de, is_red_flag, is_active, sort_order, sectors, is_follow_up, follow_up_question_key, follow_up_condition) select v.id, c.id, $txt$pc-3$txt$, $txt$Does the company have an efficient process for talent acquisition?$txt$, $txt$Verfügt das Unternehmen über einen effizienten Prozess zur Talentgewinnung?$txt$, null, null, false, true, 170, null, false, null, null from public.questionnaire_versions v join public.qv_categories c on c.version_id = v.id and c.key = $txt$people_culture$txt$ where v.version = 1;
insert into public.question_options (question_id, option_key, text_en, text_de, score, sort_order) select id, 'optimal', $txt$Professional employer branding; structured onboarding processes; talent pipeline established$txt$, $txt$Professionelles Employer Branding; strukturiertes Onboarding; Talent-Pipeline etabliert$txt$, 2, 0 from public.qv_questions where question_key = $txt$pc-3$txt$;
insert into public.question_options (question_id, option_key, text_en, text_de, score, sort_order) select id, 'good', $txt$Recruiting functions well reactively; website and external appearance are high-quality$txt$, $txt$Recruiting funktioniert reaktiv gut; Website und Außenauftritt sind hochwertig$txt$, 1, 1 from public.qv_questions where question_key = $txt$pc-3$txt$;
insert into public.question_options (question_id, option_key, text_en, text_de, score, sort_order) select id, 'low', $txt$No strategy against skilled labor shortage; open positions remain unfilled for months$txt$, $txt$Keine Strategie gegen den Fachkräftemangel; offene Stellen bleiben monatelang unbesetzt$txt$, 0, 2 from public.qv_questions where question_key = $txt$pc-3$txt$;

insert into public.qv_questions (version_id, category_id, question_key, text_en, text_de, info_en, info_de, is_red_flag, is_active, sort_order, sectors, is_follow_up, follow_up_question_key, follow_up_condition) select v.id, c.id, $txt$lc-1$txt$, $txt$Are ownership ratios and transfer chains absolutely clear?$txt$, $txt$Sind Beteiligungsverhältnisse und Übertragungsketten vollständig klar?$txt$, $txt$Complex or unclear ownership structures are a common deal-breaker. Acquirers need a clean, unambiguous shareholder register.$txt$, $txt$Komplexe oder unklare Eigentümerstrukturen sind ein häufiger Deal-Breaker. Käufer benötigen eine saubere, eindeutige Gesellschafterliste.$txt$, true, true, 180, null, false, null, null from public.questionnaire_versions v join public.qv_categories c on c.version_id = v.id and c.key = $txt$legal_cleanliness$txt$ where v.version = 1;
insert into public.question_options (question_id, option_key, text_en, text_de, score, sort_order) select id, 'optimal', $txt$Clear shareholder structure; drag-along rights in contract; transaction capability secured$txt$, $txt$Klare Gesellschafterstruktur; Drag-along-Rechte im Vertrag; Transaktionsfähigkeit gesichert$txt$, 2, 0 from public.qv_questions where question_key = $txt$lc-1$txt$;
insert into public.question_options (question_id, option_key, text_en, text_de, score, sort_order) select id, 'good', $txt$Transfer chain documentation complete; coordination among shareholders done$txt$, $txt$Dokumentation der Übertragungskette vollständig; Abstimmung der Gesellschafter erfolgt$txt$, 1, 1 from public.qv_questions where question_key = $txt$lc-1$txt$;
insert into public.question_options (question_id, option_key, text_en, text_de, score, sort_order) select id, 'low', $txt$Complex or unclear ownership; risk of blockades by minorities$txt$, $txt$Komplexe oder unklare Eigentümerschaft; Blockaderisiko durch Minderheiten$txt$, 0, 2 from public.qv_questions where question_key = $txt$lc-1$txt$;

insert into public.qv_questions (version_id, category_id, question_key, text_en, text_de, info_en, info_de, is_red_flag, is_active, sort_order, sectors, is_follow_up, follow_up_question_key, follow_up_condition) select v.id, c.id, $txt$lc-2$txt$, $txt$Do trademarks, patents, domains, and software code legally belong to the company?$txt$, $txt$Gehören Marken, Patente, Domains und Softwarecode rechtlich dem Unternehmen?$txt$, null, null, false, true, 190, null, false, null, null from public.questionnaire_versions v join public.qv_categories c on c.version_id = v.id and c.key = $txt$legal_cleanliness$txt$ where v.version = 1;
insert into public.question_options (question_id, option_key, text_en, text_de, score, sort_order) select id, 'optimal', $txt$All IP rights globally secured and owned by company; no IP held by owner personally$txt$, $txt$Alle IP-Rechte global gesichert und im Eigentum der Gesellschaft; kein IP privat beim Inhaber$txt$, 2, 0 from public.qv_questions where question_key = $txt$lc-2$txt$;
insert into public.question_options (question_id, option_key, text_en, text_de, score, sort_order) select id, 'good', $txt$Trademark and title protection registered; intellectual property inventory completed$txt$, $txt$Marken- und Titelschutz eingetragen; IP-Inventar abgeschlossen$txt$, 1, 1 from public.qv_questions where question_key = $txt$lc-2$txt$;
insert into public.question_options (question_id, option_key, text_en, text_de, score, sort_order) select id, 'low', $txt$IP rights unclear or partially in private ownership; no protection rights registered$txt$, $txt$IP-Rechte unklar oder teilweise im Privateigentum; keine Schutzrechte eingetragen$txt$, 0, 2 from public.qv_questions where question_key = $txt$lc-2$txt$;

insert into public.qv_questions (version_id, category_id, question_key, text_en, text_de, info_en, info_de, is_red_flag, is_active, sort_order, sectors, is_follow_up, follow_up_question_key, follow_up_condition) select v.id, c.id, $txt$lc-4$txt$, $txt$Are data protection (GDPR), taxes, and regulations fully complied with?$txt$, $txt$Werden Datenschutz (DSGVO), Steuern und Regulatorik vollständig eingehalten?$txt$, null, null, false, true, 200, null, false, null, null from public.questionnaire_versions v join public.qv_categories c on c.version_id = v.id and c.key = $txt$legal_cleanliness$txt$ where v.version = 1;
insert into public.question_options (question_id, option_key, text_en, text_de, score, sort_order) select id, 'optimal', $txt$Data protection officer appointed; compliance system audited; no tax risks$txt$, $txt$Datenschutzbeauftragter bestellt; Compliance-System geprüft; keine steuerlichen Risiken$txt$, 2, 0 from public.qv_questions where question_key = $txt$lc-4$txt$;
insert into public.question_options (question_id, option_key, text_en, text_de, score, sort_order) select id, 'good', $txt$GDPR implemented; social security audit completed; tax structure reviewed$txt$, $txt$DSGVO umgesetzt; Sozialversicherungsprüfung abgeschlossen; Steuerstruktur geprüft$txt$, 1, 1 from public.qv_questions where question_key = $txt$lc-4$txt$;
insert into public.question_options (question_id, option_key, text_en, text_de, score, sort_order) select id, 'low', $txt$Significant data protection gaps; unclear tax risks; no compliance control$txt$, $txt$Erhebliche Datenschutzlücken; unklare steuerliche Risiken; keine Compliance-Kontrolle$txt$, 0, 2 from public.qv_questions where question_key = $txt$lc-4$txt$;

insert into public.qv_questions (version_id, category_id, question_key, text_en, text_de, info_en, info_de, is_red_flag, is_active, sort_order, sectors, is_follow_up, follow_up_question_key, follow_up_condition) select v.id, c.id, $txt$ft-3$txt$, $txt$Are margins (EBITDA) sustainable, adjusted for one-time effects, and backed by cash flow?$txt$, $txt$Sind die Margen (EBITDA) nachhaltig, um Einmaleffekte bereinigt und durch Cashflow gedeckt?$txt$, null, null, false, true, 210, null, false, null, null from public.questionnaire_versions v join public.qv_categories c on c.version_id = v.id and c.key = $txt$financial_transparency$txt$ where v.version = 1;
insert into public.question_options (question_id, option_key, text_en, text_de, score, sort_order) select id, 'optimal', $txt$High EBITDA margin above industry average; stable operating cash flow; clear documentation of one-time effects$txt$, $txt$Hohe EBITDA-Marge über Branchendurchschnitt; stabiler operativer Cashflow; Einmaleffekte klar dokumentiert$txt$, 2, 0 from public.qv_questions where question_key = $txt$ft-3$txt$;
insert into public.question_options (question_id, option_key, text_en, text_de, score, sort_order) select id, 'good', $txt$Solid profitability; one-time effects documented but not fully analyzed$txt$, $txt$Solide Profitabilität; Einmaleffekte dokumentiert, aber nicht vollständig analysiert$txt$, 1, 1 from public.qv_questions where question_key = $txt$ft-3$txt$;
insert into public.question_options (question_id, option_key, text_en, text_de, score, sort_order) select id, 'low', $txt$Declining or volatile margins; high dependency on one-time effects; unclear operational profitability$txt$, $txt$Sinkende oder volatile Margen; hohe Abhängigkeit von Einmaleffekten; unklare operative Profitabilität$txt$, 0, 2 from public.qv_questions where question_key = $txt$ft-3$txt$;

insert into public.qv_questions (version_id, category_id, question_key, text_en, text_de, info_en, info_de, is_red_flag, is_active, sort_order, sectors, is_follow_up, follow_up_question_key, follow_up_condition) select v.id, c.id, $txt$ft-5$txt$, $txt$Are private assets, shareholder loans, and pensions strictly separated from the operating business?$txt$, $txt$Sind Privatvermögen, Gesellschafterdarlehen und Pensionen strikt vom operativen Geschäft getrennt?$txt$, $txt$Commingled personal expenses are a red flag in due diligence and can distort EBITDA calculations.$txt$, $txt$Vermischte Privatkosten sind ein Warnsignal in der Due Diligence und können die EBITDA-Berechnung verzerren.$txt$, true, true, 220, null, false, null, null from public.questionnaire_versions v join public.qv_categories c on c.version_id = v.id and c.key = $txt$financial_transparency$txt$ where v.version = 1;
insert into public.question_options (question_id, option_key, text_en, text_de, score, sort_order) select id, 'optimal', $txt$Complete separation of private and corporate assets; net debt optimized; no off-balance sheet liabilities$txt$, $txt$Vollständige Trennung von Privat- und Firmenvermögen; Net Debt optimiert; keine außerbilanziellen Verpflichtungen$txt$, 2, 0 from public.qv_questions where question_key = $txt$ft-5$txt$;
insert into public.question_options (question_id, option_key, text_en, text_de, score, sort_order) select id, 'good', $txt$Separation largely achieved; pension obligations identified and spin-off in preparation$txt$, $txt$Trennung weitgehend erreicht; Pensionsverpflichtungen identifiziert, Auslagerung in Vorbereitung$txt$, 1, 1 from public.qv_questions where question_key = $txt$ft-5$txt$;
insert into public.question_options (question_id, option_key, text_en, text_de, score, sort_order) select id, 'low', $txt$Mixing of private costs; complex shareholder claims; significant hidden liabilities in balance sheet$txt$, $txt$Vermischung privater Kosten; komplexe Gesellschafteransprüche; erhebliche stille Lasten in der Bilanz$txt$, 0, 2 from public.qv_questions where question_key = $txt$ft-5$txt$;

insert into public.qv_questions (version_id, category_id, question_key, text_en, text_de, info_en, info_de, is_red_flag, is_active, sort_order, sectors, is_follow_up, follow_up_question_key, follow_up_condition) select v.id, c.id, $txt$oi-4$txt$, $txt$Has a potential management buyout or external management handover been tested?$txt$, $txt$Wurde ein möglicher Management-Buy-out oder eine externe Führungsübergabe getestet?$txt$, null, null, false, true, 230, null, false, null, null from public.questionnaire_versions v join public.qv_categories c on c.version_id = v.id and c.key = $txt$owner_independence$txt$ where v.version = 1;
insert into public.question_options (question_id, option_key, text_en, text_de, score, sort_order) select id, 'optimal', $txt$Succession scenario successfully tested; external management fully onboarded$txt$, $txt$Nachfolgeszenario erfolgreich getestet; externes Management vollständig eingearbeitet$txt$, 2, 0 from public.qv_questions where question_key = $txt$oi-4$txt$;
insert into public.question_options (question_id, option_key, text_en, text_de, score, sort_order) select id, 'good', $txt$Qualified successors identified; handover plan for post-merger phase exists$txt$, $txt$Qualifizierte Nachfolger identifiziert; Übergabeplan für die Post-Merger-Phase vorhanden$txt$, 1, 1 from public.qv_questions where question_key = $txt$oi-4$txt$;
insert into public.question_options (question_id, option_key, text_en, text_de, score, sort_order) select id, 'low', $txt$No succession plan; owner is the only authorized representative$txt$, $txt$Kein Nachfolgeplan; der Inhaber ist der einzige Vertretungsberechtigte$txt$, 0, 2 from public.qv_questions where question_key = $txt$oi-4$txt$;

insert into public.qv_questions (version_id, category_id, question_key, text_en, text_de, info_en, info_de, is_red_flag, is_active, sort_order, sectors, is_follow_up, follow_up_question_key, follow_up_condition) select v.id, c.id, $txt$mp-4$txt$, $txt$Is there a documented product/service roadmap for the next 24 months?$txt$, $txt$Gibt es eine dokumentierte Produkt-/Leistungs-Roadmap für die nächsten 24 Monate?$txt$, null, null, false, true, 240, null, false, null, null from public.questionnaire_versions v join public.qv_categories c on c.version_id = v.id and c.key = $txt$market_position$txt$ where v.version = 1;
insert into public.question_options (question_id, option_key, text_en, text_de, score, sort_order) select id, 'optimal', $txt$Structured innovation process; roadmap for new products/services is funded and started$txt$, $txt$Strukturierter Innovationsprozess; Roadmap für neue Produkte/Leistungen ist finanziert und gestartet$txt$, 2, 0 from public.qv_questions where question_key = $txt$mp-4$txt$;
insert into public.question_options (question_id, option_key, text_en, text_de, score, sort_order) select id, 'good', $txt$Continuous portfolio development; initial concepts for digitalization/expansion available$txt$, $txt$Kontinuierliche Portfolioentwicklung; erste Konzepte für Digitalisierung/Expansion vorhanden$txt$, 1, 1 from public.qv_questions where question_key = $txt$mp-4$txt$;
insert into public.question_options (question_id, option_key, text_en, text_de, score, sort_order) select id, 'low', $txt$Focus on maintaining status quo; no significant R&D investments or future planning$txt$, $txt$Fokus auf Status quo; keine wesentlichen F&E-Investitionen oder Zukunftsplanung$txt$, 0, 2 from public.qv_questions where question_key = $txt$mp-4$txt$;

insert into public.qv_questions (version_id, category_id, question_key, text_en, text_de, info_en, info_de, is_red_flag, is_active, sort_order, sectors, is_follow_up, follow_up_question_key, follow_up_condition) select v.id, c.id, $txt$cs-2$txt$, $txt$Can critical supplies/services be sourced through alternative sources (multi-sourcing)?$txt$, $txt$Können kritische Zulieferungen/Leistungen über Alternativquellen bezogen werden (Multi-Sourcing)?$txt$, null, null, false, true, 250, null, false, null, null from public.questionnaire_versions v join public.qv_categories c on c.version_id = v.id and c.key = $txt$customer_supplier$txt$ where v.version = 1;
insert into public.question_options (question_id, option_key, text_en, text_de, score, sort_order) select id, 'optimal', $txt$Complete multi-sourcing; supplier contracts market-standard and short-term adjustable$txt$, $txt$Vollständiges Multi-Sourcing; Lieferantenverträge marktüblich und kurzfristig anpassbar$txt$, 2, 0 from public.qv_questions where question_key = $txt$cs-2$txt$;
insert into public.question_options (question_id, option_key, text_en, text_de, score, sort_order) select id, 'good', $txt$Dependency on few suppliers; alternatives identified and qualified$txt$, $txt$Abhängigkeit von wenigen Lieferanten; Alternativen identifiziert und qualifiziert$txt$, 1, 1 from public.qv_questions where question_key = $txt$cs-2$txt$;
insert into public.question_options (question_id, option_key, text_en, text_de, score, sort_order) select id, 'low', $txt$Single-source dependency for business-critical components; no alternative options$txt$, $txt$Single-Source-Abhängigkeit bei geschäftskritischen Komponenten; keine Alternativen$txt$, 0, 2 from public.qv_questions where question_key = $txt$cs-2$txt$;

insert into public.qv_questions (version_id, category_id, question_key, text_en, text_de, info_en, info_de, is_red_flag, is_active, sort_order, sectors, is_follow_up, follow_up_question_key, follow_up_condition) select v.id, c.id, $txt$ps-4$txt$, $txt$Are internal workflows (ERP/CRM) consistently digital?$txt$, $txt$Sind interne Abläufe (ERP/CRM) durchgängig digital?$txt$, null, null, false, true, 260, null, false, null, null from public.questionnaire_versions v join public.qv_categories c on c.version_id = v.id and c.key = $txt$processes_scalability$txt$ where v.version = 1;
insert into public.question_options (question_id, option_key, text_en, text_de, score, sort_order) select id, 'optimal', $txt$End-to-end digitalized value chain; data available in real-time for decisions$txt$, $txt$End-to-end digitalisierte Wertschöpfungskette; Daten in Echtzeit für Entscheidungen verfügbar$txt$, 2, 0 from public.qv_questions where question_key = $txt$ps-4$txt$;
insert into public.question_options (question_id, option_key, text_en, text_de, score, sort_order) select id, 'good', $txt$Central systems introduced; media breaks being gradually eliminated$txt$, $txt$Zentrale Systeme eingeführt; Medienbrüche werden schrittweise beseitigt$txt$, 1, 1 from public.qv_questions where question_key = $txt$ps-4$txt$;
insert into public.question_options (question_id, option_key, text_en, text_de, score, sort_order) select id, 'low', $txt$Paper-based processes; Excel lists as primary control tool; no system networking$txt$, $txt$Papierbasierte Prozesse; Excel-Listen als primäres Steuerungsinstrument; keine Systemvernetzung$txt$, 0, 2 from public.qv_questions where question_key = $txt$ps-4$txt$;

insert into public.qv_questions (version_id, category_id, question_key, text_en, text_de, info_en, info_de, is_red_flag, is_active, sort_order, sectors, is_follow_up, follow_up_question_key, follow_up_condition) select v.id, c.id, $txt$pc-4$txt$, $txt$Is the corporate culture aligned with sustainability and ESG standards?$txt$, $txt$Ist die Unternehmenskultur auf Nachhaltigkeit und ESG-Standards ausgerichtet?$txt$, null, null, false, true, 270, null, false, null, null from public.questionnaire_versions v join public.qv_categories c on c.version_id = v.id and c.key = $txt$people_culture$txt$ where v.version = 1;
insert into public.question_options (question_id, option_key, text_en, text_de, score, sort_order) select id, 'optimal', $txt$ESG management anchored at leadership level; sustainability report exists; compliance lived$txt$, $txt$ESG-Management auf Führungsebene verankert; Nachhaltigkeitsbericht vorhanden; Compliance gelebt$txt$, 2, 0 from public.qv_questions where question_key = $txt$pc-4$txt$;
insert into public.question_options (question_id, option_key, text_en, text_de, score, sort_order) select id, 'good', $txt$ESG topics in focus; initial measures documented$txt$, $txt$ESG-Themen im Fokus; erste Maßnahmen dokumentiert$txt$, 1, 1 from public.qv_questions where question_key = $txt$pc-4$txt$;
insert into public.question_options (question_id, option_key, text_en, text_de, score, sort_order) select id, 'low', $txt$No ESG strategy; focus purely on short-term profitability without social responsibility$txt$, $txt$Keine ESG-Strategie; Fokus rein auf kurzfristige Profitabilität ohne soziale Verantwortung$txt$, 0, 2 from public.qv_questions where question_key = $txt$pc-4$txt$;

insert into public.qv_questions (version_id, category_id, question_key, text_en, text_de, info_en, info_de, is_red_flag, is_active, sort_order, sectors, is_follow_up, follow_up_question_key, follow_up_condition) select v.id, c.id, $txt$lc-3$txt$, $txt$Are employment, customer, and lease contracts current and do they contain change-of-control clauses?$txt$, $txt$Sind Arbeits-, Kunden- und Mietverträge aktuell und enthalten sie Change-of-Control-Klauseln?$txt$, null, null, false, true, 280, null, false, null, null from public.questionnaire_versions v join public.qv_categories c on c.version_id = v.id and c.key = $txt$legal_cleanliness$txt$ where v.version = 1;
insert into public.question_options (question_id, option_key, text_en, text_de, score, sort_order) select id, 'optimal', $txt$All contracts up to date; change-of-control clauses reviewed and optimized$txt$, $txt$Alle Verträge aktuell; Change-of-Control-Klauseln geprüft und optimiert$txt$, 2, 0 from public.qv_questions where question_key = $txt$lc-3$txt$;
insert into public.question_options (question_id, option_key, text_en, text_de, score, sort_order) select id, 'good', $txt$Contracts documented and largely market-standard; CoC renegotiations ongoing$txt$, $txt$Verträge dokumentiert und weitgehend marktüblich; CoC-Nachverhandlungen laufen$txt$, 1, 1 from public.qv_questions where question_key = $txt$lc-3$txt$;
insert into public.question_options (question_id, option_key, text_en, text_de, score, sort_order) select id, 'low', $txt$Verbal side agreements; outdated employment contracts; critical CoC blockades unresolved$txt$, $txt$Mündliche Nebenabreden; veraltete Arbeitsverträge; kritische CoC-Blockaden ungelöst$txt$, 0, 2 from public.qv_questions where question_key = $txt$lc-3$txt$;

insert into public.qv_questions (version_id, category_id, question_key, text_en, text_de, info_en, info_de, is_red_flag, is_active, sort_order, sectors, is_follow_up, follow_up_question_key, follow_up_condition) select v.id, c.id, $txt$lc-5$txt$, $txt$Are there no ongoing or threatening legal proceedings?$txt$, $txt$Bestehen keine laufenden oder drohenden Rechtsstreitigkeiten?$txt$, null, null, false, true, 290, null, false, null, null from public.questionnaire_versions v join public.qv_categories c on c.version_id = v.id and c.key = $txt$legal_cleanliness$txt$ where v.version = 1;
insert into public.question_options (question_id, option_key, text_en, text_de, score, sort_order) select id, 'optimal', $txt$No ongoing proceedings; risk management for potential claims established$txt$, $txt$Keine laufenden Verfahren; Risikomanagement für potenzielle Ansprüche etabliert$txt$, 2, 0 from public.qv_questions where question_key = $txt$lc-5$txt$;
insert into public.question_options (question_id, option_key, text_en, text_de, score, sort_order) select id, 'good', $txt$Insignificant proceedings documented; provisions made; settlements in preparation$txt$, $txt$Unwesentliche Verfahren dokumentiert; Rückstellungen gebildet; Vergleiche in Vorbereitung$txt$, 1, 1 from public.qv_questions where question_key = $txt$lc-5$txt$;
insert into public.question_options (question_id, option_key, text_en, text_de, score, sort_order) select id, 'low', $txt$Threatening or ongoing processes with high dispute value; existential legal risks$txt$, $txt$Drohende oder laufende Verfahren mit hohem Streitwert; existenzielle Rechtsrisiken$txt$, 0, 2 from public.qv_questions where question_key = $txt$lc-5$txt$;

insert into public.qv_questions (version_id, category_id, question_key, text_en, text_de, info_en, info_de, is_red_flag, is_active, sort_order, sectors, is_follow_up, follow_up_question_key, follow_up_condition) select v.id, c.id, $txt$ft-6$txt$, $txt$What proportion of IT services revenue comes from recurring managed-service retainers versus one-off project work?$txt$, $txt$Welcher Anteil des IT-Services-Umsatzes stammt aus wiederkehrenden Managed-Service-Retainern statt aus Einzelprojekten?$txt$, $txt$Acquirers apply significant valuation discounts to pure project businesses. A retainer base above 40% fundamentally changes the quality-of-earnings narrative.$txt$, $txt$Käufer setzen bei reinen Projektgeschäften deutliche Bewertungsabschläge an. Eine Retainer-Basis über 40% verändert die Quality-of-Earnings-Story grundlegend.$txt$, false, true, 300, array['it_services']::text[], false, null, null from public.questionnaire_versions v join public.qv_categories c on c.version_id = v.id and c.key = $txt$financial_transparency$txt$ where v.version = 1;
insert into public.question_options (question_id, option_key, text_en, text_de, score, sort_order) select id, 'optimal', $txt$Over 50% of revenue from multi-year managed service or retainer contracts; project work fills capacity only$txt$, $txt$Über 50% des Umsatzes aus mehrjährigen Managed-Service- oder Retainer-Verträgen; Projekte füllen nur Kapazitäten$txt$, 2, 0 from public.qv_questions where question_key = $txt$ft-6$txt$;
insert into public.question_options (question_id, option_key, text_en, text_de, score, sort_order) select id, 'good', $txt$30-50% recurring retainer revenue; active effort to convert project clients to retained relationships$txt$, $txt$30-50% wiederkehrender Retainer-Umsatz; aktive Umstellung von Projektkunden auf Retainer$txt$, 1, 1 from public.qv_questions where question_key = $txt$ft-6$txt$;
insert into public.question_options (question_id, option_key, text_en, text_de, score, sort_order) select id, 'low', $txt$Predominantly project-based; less than 30% recurring; revenue highly dependent on new contract wins$txt$, $txt$Überwiegend projektbasiert; unter 30% wiederkehrend; Umsatz stark von Neuaufträgen abhängig$txt$, 0, 2 from public.qv_questions where question_key = $txt$ft-6$txt$;

insert into public.qv_questions (version_id, category_id, question_key, text_en, text_de, info_en, info_de, is_red_flag, is_active, sort_order, sectors, is_follow_up, follow_up_question_key, follow_up_condition) select v.id, c.id, $txt$mp-5$txt$, $txt$What is your Net Revenue Retention (NRR) rate, and how has Annual Recurring Revenue (ARR) trended over the last 12 months?$txt$, $txt$Wie hoch ist Ihre Net Revenue Retention (NRR) und wie hat sich der ARR in den letzten 12 Monaten entwickelt?$txt$, $txt$NRR above 100% signals that existing customers are expanding - a primary valuation driver for SaaS acquirers. ARR growth trajectory is often more important than absolute revenue.$txt$, $txt$Eine NRR über 100% zeigt, dass Bestandskunden ausbauen - ein zentraler Bewertungstreiber für SaaS-Käufer. Der ARR-Wachstumspfad ist oft wichtiger als der absolute Umsatz.$txt$, false, true, 310, array['saas','hr_tech']::text[], false, null, null from public.questionnaire_versions v join public.qv_categories c on c.version_id = v.id and c.key = $txt$market_position$txt$ where v.version = 1;
insert into public.question_options (question_id, option_key, text_en, text_de, score, sort_order) select id, 'optimal', $txt$NRR above 110%; ARR growing >25% year-on-year; churn well below industry average$txt$, $txt$NRR über 110%; ARR-Wachstum >25% im Jahresvergleich; Churn deutlich unter Branchendurchschnitt$txt$, 2, 0 from public.qv_questions where question_key = $txt$mp-5$txt$;
insert into public.question_options (question_id, option_key, text_en, text_de, score, sort_order) select id, 'good', $txt$NRR between 90-110%; ARR stable or growing modestly; churn tracked and managed$txt$, $txt$NRR zwischen 90-110%; ARR stabil oder moderat wachsend; Churn wird erfasst und gesteuert$txt$, 1, 1 from public.qv_questions where question_key = $txt$mp-5$txt$;
insert into public.question_options (question_id, option_key, text_en, text_de, score, sort_order) select id, 'low', $txt$NRR below 90%; ARR flat or declining; churn not systematically measured$txt$, $txt$NRR unter 90%; ARR stagnierend oder rückläufig; Churn wird nicht systematisch gemessen$txt$, 0, 2 from public.qv_questions where question_key = $txt$mp-5$txt$;

insert into public.qv_questions (version_id, category_id, question_key, text_en, text_de, info_en, info_de, is_red_flag, is_active, sort_order, sectors, is_follow_up, follow_up_question_key, follow_up_condition) select v.id, c.id, $txt$cyber_own_ip_mix$txt$, $txt$What share of revenue comes from your own managed services and products rather than reselling third-party licences?$txt$, $txt$Welcher Umsatzanteil stammt aus eigenen Managed Services und Produkten statt aus dem Wiederverkauf von Fremdlizenzen?$txt$, $txt$Buyers price own delivery and own IP differently from licence resale: resale revenue carries vendor dependency and thin margins, own services carry the multiple.$txt$, $txt$Käufer bewerten Eigenleistung und eigene IP anders als Lizenz-Resale: Resale-Umsatz trägt Herstellerabhängigkeit und dünne Margen, eigene Services tragen das Multiple.$txt$, false, true, 320, array['cybersecurity']::text[], false, null, null from public.questionnaire_versions v join public.qv_categories c on c.version_id = v.id and c.key = $txt$market_position$txt$ where v.version = 1;
insert into public.question_options (question_id, option_key, text_en, text_de, score, sort_order) select id, 'optimal', $txt$Own delivery dominates; third-party resale below roughly 30% of revenue$txt$, $txt$Eigenleistung dominiert; Fremdlizenz-Resale unter rund 30% des Umsatzes$txt$, 2, 0 from public.qv_questions where question_key = $txt$cyber_own_ip_mix$txt$;
insert into public.question_options (question_id, option_key, text_en, text_de, score, sort_order) select id, 'good', $txt$Balanced mix of own delivery and third-party resale$txt$, $txt$Ausgewogener Mix aus Eigenleistung und Fremdlizenz-Resale$txt$, 1, 1 from public.qv_questions where question_key = $txt$cyber_own_ip_mix$txt$;
insert into public.question_options (question_id, option_key, text_en, text_de, score, sort_order) select id, 'low', $txt$Revenue predominantly from reselling third-party licences$txt$, $txt$Umsatz überwiegend aus dem Wiederverkauf von Fremdlizenzen$txt$, 0, 2 from public.qv_questions where question_key = $txt$cyber_own_ip_mix$txt$;

insert into public.qv_questions (version_id, category_id, question_key, text_en, text_de, info_en, info_de, is_red_flag, is_active, sort_order, sectors, is_follow_up, follow_up_question_key, follow_up_condition) select v.id, c.id, $txt$cyber_certifications$txt$, $txt$Which security certifications and audit attestations does your company hold?$txt$, $txt$Welche Sicherheitszertifizierungen und Prüfnachweise hält Ihr Unternehmen?$txt$, $txt$In cybersecurity transactions, buyers verify certifications early in due diligence; a current ISO 27001 or SOC 2 report shortens the process and supports the valuation.$txt$, $txt$Bei Cybersecurity-Transaktionen prüfen Käufer Zertifizierungen früh in der Due Diligence; ein aktueller ISO-27001- oder SOC-2-Nachweis verkürzt den Prozess und stützt die Bewertung.$txt$, false, true, 330, array['cybersecurity']::text[], false, null, null from public.questionnaire_versions v join public.qv_categories c on c.version_id = v.id and c.key = $txt$processes_scalability$txt$ where v.version = 1;
insert into public.question_options (question_id, option_key, text_en, text_de, score, sort_order) select id, 'optimal', $txt$ISO 27001 or SOC 2 Type II in place; audits current, renewals scheduled$txt$, $txt$ISO 27001 oder SOC 2 Type II vorhanden; Audits aktuell, Renewals terminiert$txt$, 2, 0 from public.qv_questions where question_key = $txt$cyber_certifications$txt$;
insert into public.question_options (question_id, option_key, text_en, text_de, score, sort_order) select id, 'good', $txt$Certification in progress or partial attestations (e.g. TISAX, BSI baseline protection)$txt$, $txt$Zertifizierung läuft oder Teilnachweise (z. B. TISAX, BSI-Grundschutz)$txt$, 1, 1 from public.qv_questions where question_key = $txt$cyber_certifications$txt$;
insert into public.question_options (question_id, option_key, text_en, text_de, score, sort_order) select id, 'low', $txt$No formal security certification or attestation$txt$, $txt$Keine formale Sicherheitszertifizierung$txt$, 0, 2 from public.qv_questions where question_key = $txt$cyber_certifications$txt$;

insert into public.qv_questions (version_id, category_id, question_key, text_en, text_de, info_en, info_de, is_red_flag, is_active, sort_order, sectors, is_follow_up, follow_up_question_key, follow_up_condition) select v.id, c.id, $txt$cyber_key_experts$txt$, $txt$How dependent is service delivery on a small number of certified security experts?$txt$, $txt$Wie stark hängt die Leistungserbringung an wenigen zertifizierten Security-Experten?$txt$, $txt$Scarce security talent is a core diligence topic: buyers examine whether delivery survives the departure of individual certified experts.$txt$, $txt$Knappes Security-Personal ist ein Kernthema der Due Diligence: Käufer prüfen, ob die Leistungserbringung den Abgang einzelner zertifizierter Experten übersteht.$txt$, false, true, 340, array['cybersecurity']::text[], false, null, null from public.questionnaire_versions v join public.qv_categories c on c.version_id = v.id and c.key = $txt$people_culture$txt$ where v.version = 1;
insert into public.question_options (question_id, option_key, text_en, text_de, score, sort_order) select id, 'optimal', $txt$Expertise spread across a stable team; key certifications held by several people per domain; cover documented$txt$, $txt$Know-how auf ein stabiles Team verteilt; Schlüsselzertifikate mehrfach je Themenfeld; Vertretung dokumentiert$txt$, 2, 0 from public.qv_questions where question_key = $txt$cyber_key_experts$txt$;
insert into public.question_options (question_id, option_key, text_en, text_de, score, sort_order) select id, 'good', $txt$Some concentration on individual experts; deputies partly in place$txt$, $txt$Teilweise Konzentration auf einzelne Experten; Vertretung teilweise geregelt$txt$, 1, 1 from public.qv_questions where question_key = $txt$cyber_key_experts$txt$;
insert into public.question_options (question_id, option_key, text_en, text_de, score, sort_order) select id, 'low', $txt$Delivery depends on one or two key experts without documented cover$txt$, $txt$Leistung hängt an ein bis zwei Schlüsselpersonen ohne dokumentierte Vertretung$txt$, 0, 2 from public.qv_questions where question_key = $txt$cyber_key_experts$txt$;

insert into public.qv_questions (version_id, category_id, question_key, text_en, text_de, info_en, info_de, is_red_flag, is_active, sort_order, sectors, is_follow_up, follow_up_question_key, follow_up_condition) select v.id, c.id, $txt$oi-1-fu$txt$, $txt$Is there a documented deputy or succession plan that would allow the business to operate for 90+ days without the owner?$txt$, $txt$Gibt es einen dokumentierten Vertretungs- oder Nachfolgeplan, mit dem das Unternehmen 90+ Tage ohne den Inhaber arbeiten könnte?$txt$, $txt$Even if owner dependency is currently high, a credible written transition plan signals to buyers that you are aware of the risk and have begun addressing it.$txt$, $txt$Auch bei hoher Inhaberabhängigkeit signalisiert ein belastbarer schriftlicher Übergabeplan Käufern, dass das Risiko erkannt und angegangen wird.$txt$, false, true, 350, null, true, $txt$oi-1$txt$, 'score_0' from public.questionnaire_versions v join public.qv_categories c on c.version_id = v.id and c.key = $txt$owner_independence$txt$ where v.version = 1;
insert into public.question_options (question_id, option_key, text_en, text_de, score, sort_order) select id, 'optimal', $txt$Formal written succession plan exists; deputy has been active in key decisions for at least 6 months$txt$, $txt$Formaler schriftlicher Nachfolgeplan vorhanden; die Vertretung ist seit mindestens 6 Monaten in Schlüsselentscheidungen eingebunden$txt$, 2, 0 from public.qv_questions where question_key = $txt$oi-1-fu$txt$;
insert into public.question_options (question_id, option_key, text_en, text_de, score, sort_order) select id, 'good', $txt$Deputy identified and partially trained; succession plan drafted but not yet tested$txt$, $txt$Vertretung identifiziert und teilweise eingearbeitet; Nachfolgeplan entworfen, aber noch nicht getestet$txt$, 1, 1 from public.qv_questions where question_key = $txt$oi-1-fu$txt$;
insert into public.question_options (question_id, option_key, text_en, text_de, score, sort_order) select id, 'low', $txt$No deputy or succession plan; owner is sole decision-maker with no documented handover procedure$txt$, $txt$Keine Vertretung und kein Nachfolgeplan; der Inhaber entscheidet allein, ohne dokumentierte Übergabe$txt$, 0, 2 from public.qv_questions where question_key = $txt$oi-1-fu$txt$;

insert into public.qv_questions (version_id, category_id, question_key, text_en, text_de, info_en, info_de, is_red_flag, is_active, sort_order, sectors, is_follow_up, follow_up_question_key, follow_up_condition) select v.id, c.id, $txt$cs-1-fu$txt$, $txt$What would be the quantified financial impact if your largest customer were lost, and is there an active diversification strategy in place?$txt$, $txt$Welche quantifizierte finanzielle Auswirkung hätte der Verlust Ihres größten Kunden, und gibt es eine aktive Diversifizierungsstrategie?$txt$, $txt$Concentration risk must be quantified and mitigated, not just acknowledged. Buyers need to see that you understand the exposure and are actively reducing it.$txt$, $txt$Konzentrationsrisiko muss quantifiziert und gemindert werden, nicht nur benannt. Käufer wollen sehen, dass das Exposure verstanden und aktiv reduziert wird.$txt$, false, true, 360, null, true, $txt$cs-1$txt$, 'score_0' from public.questionnaire_versions v join public.qv_categories c on c.version_id = v.id and c.key = $txt$customer_supplier$txt$ where v.version = 1;
insert into public.question_options (question_id, option_key, text_en, text_de, score, sort_order) select id, 'optimal', $txt$Financial impact quantified; active diversification programme underway; retention agreements signed with top clients$txt$, $txt$Finanzielle Auswirkung quantifiziert; aktives Diversifizierungsprogramm läuft; Bindungsvereinbarungen mit Top-Kunden unterzeichnet$txt$, 2, 0 from public.qv_questions where question_key = $txt$cs-1-fu$txt$;
insert into public.question_options (question_id, option_key, text_en, text_de, score, sort_order) select id, 'good', $txt$Impact understood informally; some retention measures in place; diversification on the roadmap$txt$, $txt$Auswirkung informell verstanden; einzelne Bindungsmaßnahmen vorhanden; Diversifizierung auf der Roadmap$txt$, 1, 1 from public.qv_questions where question_key = $txt$cs-1-fu$txt$;
insert into public.question_options (question_id, option_key, text_en, text_de, score, sort_order) select id, 'low', $txt$No formal analysis of concentration risk; no diversification strategy; relationship relies solely on personal owner ties$txt$, $txt$Keine formale Analyse des Konzentrationsrisikos; keine Diversifizierungsstrategie; die Beziehung beruht allein auf persönlichen Kontakten des Inhabers$txt$, 0, 2 from public.qv_questions where question_key = $txt$cs-1-fu$txt$;

insert into public.qv_questions (version_id, category_id, question_key, text_en, text_de, info_en, info_de, is_red_flag, is_active, sort_order, sectors, is_follow_up, follow_up_question_key, follow_up_condition) select v.id, c.id, $txt$ft-2-fu$txt$, $txt$Are monthly or quarterly management accounts maintained, and have they been reviewed by an external accountant?$txt$, $txt$Werden monatliche oder quartalsweise Management Accounts geführt und wurden sie von einem externen Buchhalter geprüft?$txt$, $txt$In the absence of full audited accounts, buyers look for the next-best evidence of financial rigour. Regularly reviewed management accounts significantly reduce perceived financial risk.$txt$, $txt$Ohne vollständig testierte Abschlüsse suchen Käufer den nächstbesten Nachweis finanzieller Disziplin. Regelmäßig geprüfte Management Accounts senken das wahrgenommene Finanzrisiko deutlich.$txt$, false, true, 370, null, true, $txt$ft-2$txt$, 'score_lte_1' from public.questionnaire_versions v join public.qv_categories c on c.version_id = v.id and c.key = $txt$financial_transparency$txt$ where v.version = 1;
insert into public.question_options (question_id, option_key, text_en, text_de, score, sort_order) select id, 'optimal', $txt$Monthly management accounts produced and reviewed by an external accountant quarterly; variance analysis documented$txt$, $txt$Monatliche Management Accounts, quartalsweise von einem externen Buchhalter geprüft; Abweichungsanalyse dokumentiert$txt$, 2, 0 from public.qv_questions where question_key = $txt$ft-2-fu$txt$;
insert into public.question_options (question_id, option_key, text_en, text_de, score, sort_order) select id, 'good', $txt$Quarterly management accounts exist; external accountant involved at year-end only$txt$, $txt$Quartalsweise Management Accounts vorhanden; externer Buchhalter nur zum Jahresende eingebunden$txt$, 1, 1 from public.qv_questions where question_key = $txt$ft-2-fu$txt$;
insert into public.question_options (question_id, option_key, text_en, text_de, score, sort_order) select id, 'low', $txt$No management accounts; financials prepared only for tax purposes once a year$txt$, $txt$Keine Management Accounts; Zahlen werden nur einmal jährlich für steuerliche Zwecke erstellt$txt$, 0, 2 from public.qv_questions where question_key = $txt$ft-2-fu$txt$;
